CO-1214: Replace es with json
osu-mist/meta-xe-api pull request #7
Opened 2018-10-22 17:48 UTC by ianbrown9475

2018-10-22 21:21 UTC, jaredkosanovic requested changes
One other comment is that when doing an out of bounds page number, the next, previous, and self links are gone: /xeapps?page[number]=5&page[size]=3

```
{
  "links": {
    "first": "https://oregonstateuniversity-dev.apigee.net/v1/xeapps?page%5Bnumber%5D=1&page%5Bsize%5D=3",
    "last": "https://oregonstateuniversity-dev.apigee.net/v1/xeapps?page%5Bnumber%5D=4&page%5Bsize%5D=3"
  },
  "data": []
}
```

2018-10-22 21:21 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/metaxe/MetaXEApplication.groovy
> +    private static final String XE_APPS_FILE_PATH = "scripts/get_xe_apps/xe_apps.json"
Let's make this path configurable. In our API VMs, this directory structure won't exist, so we'll want to have the json file at the root directory of the application (same directory as the jar file).

2018-10-22 21:21 UTC, jaredkosanovic commented on src/main/groovy/edu/oregonstate/mist/metaxe/XEAppsResource.groovy
> +        int lastPage = totalHits != 0 ? (totalHits + pageSize - 1).intdiv(pageSize).toInteger() : 1
This throws an exception if pageSize == 0.

```
ERROR [2018-10-22 21:07:59,051] edu.oregonstate.mist.api.jsonapi.GenericExceptionMapper: Uncaught exception
! java.lang.ArithmeticException: / by zero
! at org.codehaus.groovy.runtime.typehandling.IntegerMath.intdivImpl(IntegerMath.java:68)
! at org.codehaus.groovy.runtime.typehandling.NumberMath.intdiv(NumberMath.java:85)
! at org.codehaus.groovy.runtime.DefaultGroovyMethods.intdiv(DefaultGroovyMethods.java:14174)
! at org.codehaus.groovy.runtime.dgm$345.invoke(Unknown Source)
! at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
! at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
! at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
! at edu.oregonstate.mist.metaxe.XEAppsResource.getPaginationLinks(XEAppsResource.groovy:161)```

2018-10-24 15:27 UTC, ianbrown9475 commented on src/main/groovy/edu/oregonstate/mist/metaxe/XEAppsResource.groovy
> +        int lastPage = totalHits != 0 ? (totalHits + pageSize - 1).intdiv(pageSize).toInteger() : 1
Thanks for catching this. This should be fixed once the changes in the skeleton get merged in. Looks like right now, if pageSize or pageNumber are <= 0, they'll be replaced with the default values https://github.com/osu-mist/web-api-skeleton/blob/557053350869084e3cb6e97bf64cf6a9aa11f4f1/src/main/groovy/edu/oregonstate/mist/api/Resource.groovy#L189-L210. Based on our group discussion on pagination, I think this will later be changed so that a bad request will be returned if pageNumber or pageSize <= 0.

2018-10-24 22:32 UTC, jaredkosanovic approved these changes

2018-10-26 16:57 UTC, jaredkosanovic approved these changes

2018-10-26 17:22 UTC, merged